#!/usr/bin/env python
# Chefalizer

import sys, argparse
import pychefalizer.elex as elex
import pychefalizer.clex as clex

argparser = argparse.ArgumentParser(description="Python Cheferizer")

argparser.add_argument('-d', '--debug', default=False, action='store_true', help="Enable debugging output")

args = argparser.parse_args()

e = elex.Elex()
e.build()

with sys.stdin as fp:
	for line in fp:
		out = e.translate(line)

		if args.debug:
			sys.stderr.write("in  > " + line)
			sys.stderr.write("out > " + out)

		sys.stdout.write(out)

